### ISSUE TITLE
Can't backspace

### ISSUE THREAD

**Issue by annonymous12343** [beryllium-org/OS#95]
Hi! I installed this os on a marble pico and it works almost perfect, i just can't backspace. Im using the screen utility in kali linux.

**Comment by bill88t** [comment]
`screen`? The command? That's tested and known working. I just retested.
Maybe your keyboard layout is at fault? Any unknown characters are ignored.

If the rest of the keyboard is working you can try to run the jcurses terminal training function:
```py
[board@tws3 | ~]> py
CircuitPython 9.1.0 on Beryllium 0.5.1
Board: lilygo_twatch_s3
Type "help", "copyright", "credits" or "license" for more information.
>>> term.training() # Press backspace once and wait after sending the command.
127

>>> ^D
[board@tws3 | ~]>
```
The terminal itself so long as it supports ANSI (which `screen` does support just fine), shouldn't matter.

**Comment by annonymous12343** [comment]
Idk what was the problem, but i switched to using putty and now it works. I also have a question. How can i initialize and use a fat32 sd card? The board im using has a sd card slot onboard. Thanks!

**Comment by bill88t** [comment]
Micro/CircuitPython mounts are very broken at the moment.
They are not usable under Beryllium OS at the moment.
(Look at: https://github.com/adafruit/circuitpython/issues/9045 and https://github.com/adafruit/circuitpython/issues/8409)
I will implement my own solution very soon.

If you want the backspace fixed for screen, you can just send me the binary value that is produced from the training function.
