### ISSUE TITLE
I have the ESP32-C6 dev kit board, believe it is also supported?

### ISSUE THREAD

**Issue by Jibun-no-Kage** [beryllium-org/OS#98]
I have the ESP32-C6 dev kit board, believe it is also supported?

https://www.amazon.com/Espressif-ESP32-C6-DevKitC-1-N8-Development-Board/dp/B0BRMSDR4R?th=1

**Comment by bill88t** [comment]
ESP32-C6 is a supported chip, however I don't have the individual board, and thus have not made a board port.

For porting instructions, take a look at: [PORTING.md](https://github.com/beryllium-org/OS/blob/master/PORTING.md)

If you have created a working port, you can open a Pull Request.

**Comment by Jibun-no-Kage** [comment]
Thanks for classification, I will take a look.
